---
title: Exceções
created_at: 2009-12-23 14:29:25.387994 -02:00
filter:
 - erb
 - textile
---
p(title). <%= h(@page.title) %>

h2. Lançando uma Exceção

Uma exceção é um tipo especial de objeto, uma instância da classe **Exception** ou uma descendente dessa classe que representa um tipo de condição incomum; ela indica que algo de errado aconteceu. Quando isso ocorre, uma exceção é levantada (ou lançada). Por padrão, os programas Ruby terminam quando uma exceção ocorre. Mas é possível declarar tratadores de exceção. Um tratador (handler) de exceção é um bloco de código que é executado se uma exceção ocorre durante a execução de algum outro bloco de código. Levantar uma exceção significa parar a execução normal do programa e transferir o fluxo de controle para o código tratador da exceção onde você pode ou lidar com o problema que foi encontrado ou sair completamente do programa. O que irá acontecer - lidar com o problema ou abortar o programa - depende do que você forneceu um comando de resgate (**rescue**, que é uma parte fundamental da linguagem Ruby). Se você não forneceu este comando, o programa termina; se você forneceu, o fluxo de controle é passado ao comando **rescue**.

O Ruby tem algumas classes pré-definidas - Exceptions e  suas filhas - que lhe ajudam a lidar com erros que ocorrem em seu programa. A figura a seguir mostra a hierarquia das exceções em Ruby.

!images/exception.jpg(Hierarquia das exceções no Ruby)!

Referência: A figura acima é do livro _Programming Ruby_.

O gráfico acima mostra que a maioria das subclasses estendem uma classe conhecida como StandardError (erro padrão). Estas são as exceções "normais" que os programas Ruby tipicamente tentam tratar. As outras exceções representam condições de mais baixo nível, mais sérias ou com condições menos recuperáveis, e programas normais Ruby normalmente não tentam tratá-las.

O seguinte método lança uma exceção sempre que é chamado. Sua segunda mensagem nunca será impressa. Programa **p043raise.rb**.

<% coderay(:lang => "ruby", :line_numbers => "inline") do -%>
  # p043raise.rb
  def levanta_excecao
    puts 'Estou antes do raise.'
    raise 'Um erro ocorreu'
    puts 'Estou depois do raise'
  end
  levanta_excecao
<% end -%>

A saída é:

<% coderay(:lang => "bash", :line_numbers => "inline") do -%>
  >ruby p043raise.rb
  Estou antes do raise.
  p043raise.rb:4:in `levanta_excecao': Um erro ocorreu (RuntimeError)
      from p043raise.rb:7
  >Exit code: 1
<% end -%>

O método **raise** é do módulo Kernel. Por padrão, **raise** cria uma exceção da classe **RuntimeError**. Para levantar a exceção de uma classe específica, você pode passar o nome da classe como argumento para **raise**. Refira-se ao programa **p044inverse.rb**

<% coderay(:lang => "ruby", :line_numbers => "inline") do -%>
  # p044inverse.rb
  def inverte(x)
    raise ArgumentError, 'O argumento não é numérico' unless x.is_a? Numeric
    1.0 / x
  end
  puts inverte(2)
  puts inverte('não é um número')
<% end -%>

A saída é:

<% coderay(:lang => "bash", :line_numbers => "inline") do -%>
  >ruby p044inverse.rb
  0.5
  p044inverse.rb:3:in `inverte': O argumento não é numérico (ArgumentError)
      from p044inverse.rb:7
  >Exit code: 1
<% end -%>

Lembre-se, métodos que agem como perguntas são geralmente nomeados com um sinal de interrogação no final. **is_a?** é um método na classe Objeto e retorna verdadeiro ou falso. O modificador **unless** quando colocado no final de uma expressão significa executa a expressão antecedente ao menos que a condição seja verdadeira (ou seja, somente se ele não for verdadeira).


Definindo novas classes de exceção: Para ser ainda mais específicio sobre um erro, você pode definir sua própria subclasse de exceção:

<% coderay(:lang => "ruby", :line_numbers => "inline") do -%>
  class NotInvertibleError < StandardError
  end
<% end -%>

h2. Tratando uma Exceção

Para fazer o tratamento da exceção, nós colocamos o código que pode lançar uma exceção dentro de um  bloco **begin-end** e usamos uma ou mais cláusulas **rescue** para contar ao Ruby os tipos de exceção que queremos tratar. É importante notar que o corpo de definição de um método é um bloco **begin-end** implícito; o **begin** é omitido, e todo o corpo do método está sujeito ao tratamento de exceção, terminando com o **end** do método.

O programa p**045handexcp.rb** ilustra isso:

<% coderay(:lang => "ruby", :line_numbers => "inline") do -%>
  # p045handexcp.rb
  def levanta_e_resgata
    begin
      puts 'Estou antes do raise.'
      raise 'Um erro ocorreu'
      puts 'Estou depois do raise'
    rescue
      puts 'Fui resgatado.'
    end
    puts 'Estou depois do bloco begin.'
  end
  levanta_e_resgata
<% end -%>


A saída é:

<% coderay(:lang => "bash", :line_numbers => "inline") do -%>
  >ruby p045handexcp.rb
  Estou antes do raise.
  Fui resgatado.
  Estou depois do bloco begin.
  >Exit code: 0
<% end -%>

Observe que o o código interrompido pela exceção nunca é executado. Uma vez que a exceção é tratada, a execução continua imediatamente depois do bloco begin que a a gerou.

Se você escreve uma cláusula **rescue** sem nenhum parâmetro, o parâmetro será ajustado por padrão para **StandardError**. Cada cláusula **rescue** pode especificar múltiplas exceções para serem capturadas. No fim de cada cláusula **rescue** voce pode passar ao Ruby o nome de uma variável local para receber a exceção correspondente. Os parâmetros para a cláusula **rescue** podem também ser expressões arbitrárias (incluindo chamadas a métodos) que retornam uma classe do tipo **Exception**. Se usarmos **raise** sem parâmetros, ele relançará a exceção.

Você pode empilhar cláusulas de **rescue** em um bloco begin/rescue. Exceções não tratadas por uma cláusula rescue serão passadas para a próxima:

<% coderay(:lang => "ruby", :line_numbers => "inline") do -%>
  begin
    # -
  rescue UmTipoDeExcecao
    # -
  rescue OutroTipoDeExcecao
    # -
  else
    # -
  end
<% end -%>

Para cada cláusula **rescue** no bloco **begin**, o Ruby irá comparar a exceção levantada contra cada um dos parâmetros em questão. O casamento irá acontecer se o nome da exceção na cláusula rescue for do mesmo tipo da última exceção lançada, ou é uma superclasse dessa exceção. O código em uma cláusula **else** é executado se o código no corpo da declaração begin executa até o final sem exceções. Se uma exceção ocorrer, então a cláusula else obviamente não será executada. O uso de uma cláusula else não é particularmente comum em Ruby.


Se você quer verificar uma exceção resgatada (em que se usou o rescue). você pode mapear o objeto **Exception** para uma variável com uma cláusula rescue, como mostrado no programa **p046excpvar.rb**

<% coderay(:lang => "ruby", :line_numbers => "inline") do -%>
  # p046excpvar.rb
  begin
    raise 'Uma exceção para teste.'
  rescue Exception => e
    puts e.message
    puts e.backtrace.inspect
  end
<% end -%>


A saída é:

<% coderay(:lang => "bash", :line_numbers => "inline") do -%>
  >ruby p046excpvar.rb
  Uma exceção para teste.
  ["p046excpvar.rb:3"]
  >Exit code: 0
<% end -%>

A classe **Exception** define dois métodos que retornam detalhes a respeito da exceção. O método **message** retorna uma string que pode prover detalhes legíveis sobre o que aconteceu de errado. O outro método importante é **backtrace**. Este método retorna um array de strings que representam a pilha de chamada no ponto em que a exceção foi lançada.

Se você precisa de garantia de que algum processamento foi feito no final de um bloco de código, não considerando se uma exceção foi lançada então a cláusula **ensure** (assegurar-se) deve ser usada após o último **rescue** e deve conter um pedaço de código que será executado a medida que o bloco  termina. O bloco **ensure** sempre será executado.

Algumas exceções comuns são:

RuntimeError (está é a exceção padrão lançada pelo método **raise**), NoMethodError, NameError, IOError, TypeError e ArgumentError.

Um Exemplo: Vamos modificar o programa **p027readwrite.rb** para incluir o tratamento de exceções como mostrado no exemplo **p046xreadwrite.rb** abaixo.

<% coderay(:lang => "ruby", :line_numbers => "inline") do -%>
  # p046xreadwrite.rb
  # Abra e leia um arquivo texto
  # Note que visto que um bloco é dado, o arquivo será fechado automaticamente quando o bloco se encerra
  begin
    File.open('p014constructs.rb', 'r') do |f1|
      while line = f1.gets
        puts line
      end
    end

    # Cria um novo arquivo e escreve nele
    File.open('test.rb', 'w') do |f2|
      # use \n para pular para próxima linha
      f2.puts "Criado por Satish\nGraças a Deus!"
    end
  rescue Exception => msg
    # mostre a mensagem de erro gerada pelo sistema
    puts msg
  end
<% end -%>

<div class='box'>
Mensagens de erros impróprias podem prover informações críticas sobre uma aplicação que podem auxiliar ataques a mesma. O problema mais comum ocorre quando mensagens de erro internas como traços de pilha, dumps de bancos de dados e códigos de erro são mostrados ao usuário. Analistas de segurança veem logs e tratamentos de erro como possíveis áreas de risco. É recomendado que as aplicações em produção não usem, por exemplo, uma chamada a *puts e.backtrace.inspect* ao menos que ela esteja sendo enviada para um log que não é visível para o usuário final.
</div>

h2. Exemplo de validação

Aqui está um exemplo do livro _Ruby Cookbook_, mostrando como se pode fazer validação da entrada do usuário.

<% coderay(:lang => "ruby", :line_numbers => "inline") do -%>
  class Nome
    # Define métodos getter padrão mas não métodos setter
    attr_reader :primeiro, :ultimo
    # Quando alguém tenta escrever um primeiro nome, force regras sobre ele.
    def primeiro=(primeiro)
      if primeiro == nil or first.size == 0
        raise ArgumentError.new('Todos precisam ter um primeiro nome.')
      end
      primeiro = primeiro.dup
      primeiro[0] = primeiro[0].chr.capitalize
      @primeiro = primeiro
    end

    # Quando alguém tenta escrever um último nome, force regras sobre ele.
    def ultimo=(ultimo)
      if ultimo == nil or ultimo.size == 0
        raise ArgumentError.new('Todos devem ter um último nome.')
      end
      @ultimo = ultimo
    end

    def nome_completo
      "#{@primeiro} #{@ultimo}"
    end

    # Delega para o método setter ao invés de escrever na instância diretamente.
    def initialize(primeiro, ultimo)
      self.primeiro = primeiro
      self.ultimo = ultimo
    end
  end

  jacob = Nome.new('Jacob', 'Berendes')
  jacob.primeiro = 'Mary Sue'
  jacob.nome_completo # => "Mary Sue Berendes"
  john = Nome.new('john', 'von Neumann')
  john.nome_completo # => "John von Neumann"
  john.primeiro = 'john'
  john.primeiro # => "John"
  john.primeiro = nil
  # ArgumentError: Todos precisam ter um primeiro nome.
  Name.new('Kero, estrela internacional do futebol e artista de performance', nil)
  # ArgumentError: Todos precisam ter um último nome.
<% end -%>

A classe **Nome** armazena o primeiro e último nome das pessoas. Ele usa métodos setter para ter certeza de duas regras restritas: todos devem possuir tanto um primeiro quanto um último nome, e o primeiro nome de todas as pessoas deve começar com uma letra maiúscula. A classe **Nome** foi escrita de um modo que as regras são impostas  tanto no construtor quanto depois que o objeto foi criado. Em certas ocasiões você não confia dos dados vindos através dos métodos setter. Nestes casos você deve definir seus próprios métodos para evitar que dados ruins infectem seus objetos. Dentro de uma classe, você pode acessar diretamente as variáveis de instância. Você pode simplesmente associar a uma variável de instância e método setter não será disparado. Se você quer dispará-lo, você precisará chamá-lo explicitamente. Note como, no método **Nome#initialize** acima, chamamos os métodos **primeiro=** e **ultimo=** ao invés de atribuir a @primeiro e @ultimo. Com isso temos certeza de que o código de validação é executado para os valores iniciais de cada objeto da classe **Nome**. Não podemos apenas dizer **primeiro = primeiro**, porque *primeiro* é um nome de variável nesse método. Usamos então **self.primeiro* para executar o método **primeiro=**.

<%- page_title, page_url = next_page %>
<div class="pagination"><%= link_to(page_title + " >" , page_url) %></div>

